before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/tfsort/
    binary: tfsort
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Referencing LDFLAGS and VERSION_PKG (main) from Makefile
    ldflags: |
      -s -w
      -X 'main.version={{.Version}}'
      -X 'main.commit={{.Commit}}'
      -X 'main.date={{.Date}}'
    ignore:
      # Exclude windows/arm64 as it's not a common combination (comment out if needed)
      - goos: windows
        goarch: arm64
archives:
  - id: default
    format: tar.gz
    # Override setting to create archives in zip format for Windows
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next" # Increment patch version using incpatch
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'Merge pull request'
      - 'Merge branch'
# Configuration for GitHub Releases
release:
  github:
    owner: tjun
    name: tfsort
  # draft: true # If you want to create the release as a draft
  # prerelease: auto # If the tag name contains a prerelease suffix (e.g., -rc1), mark as prerelease
